baseURL: http://example.org/
languageCode: en-us
title: ðŸš‚derailedðŸšƒ
theme: "PaperMod"

params:
  title: Derailed
  description: derailed, a blog going off the rails
  keywords: [Blog]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  homeInfoParams:
    Title: Hello there! ðŸ˜Š
    Content: "This is derailed, an experimental blog and personal outlet! âš  Caution âš : Topics will vary widely and are often derailed."

  socialIcons:
    - name: "Twitter"
      title: "@DerailedBlog"
      url: "https://twitter.com/DerailedBlog"
    - name: "Email"
      title: "thederailedblog@gmail.com"
      url: "mailto:thederailedblog@gmail.com"
  
  ShowShareButtons: false
  ShowReadingTime: true
  ShowBreadCrumbs: true
